### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by bensonarafat** [google/generative-ai-swift#111]
### Description of the feature request:

I want to add the SDK as a pod, There is no documentation on this.

### What problem are you trying to solve with this feature?

I want to add the SDK to my flutter Plugin. The option i have is to add it to my .podspec file. 
Is this possible for me to do? 
Thank.

**Comment by paulb777** [comment]
We don't yet support integration via CocoaPods. Thanks for the feature request and we'll add it to our backlog.

**Comment by bensonarafat** [comment]
Okay, thanks

**Comment by paulb777** [comment]
https://github.com/google/generative-ai-dart includes a Flutter sample. Does that meet your needs?

**Comment by bensonarafat** [comment]
Yeah, I know about that, it was recently released which uses REST API. 

I'm also building a flutter plugin but in my case I want to interact with the native features instead. 

Using SPM is not something I'll consider other developers to do.. Becox they have to open Xcode and add it them selves. 

That's why I need to add it as cocoa pods 

Ive already developed the android part.

**Comment by paulb777** [comment]
Why is a Flutter integration to Swift SDK that uses a REST API better than a Flutter integration to a Dart SDK that uses the same REST API?

**Comment by bensonarafat** [comment]
Oh!! Is that so? Never thought of that. 
Anyways, I wanted to try something else 
And I've to complete it.

**Comment by paulb777** [comment]
Closing this feature request for now since the request has the better path of using the Dart SDK.

If there is other interest in CocoaPods, please open another feature request with the use case described.
