### ISSUE TITLE
Access gemini-1.5-pro-latest

### ISSUE THREAD

**Issue by mobilinked** [google/generative-ai-swift#128]
### Description of the feature request:

As the title, to access the gemini-1.5-pro-latest model

### What problem are you trying to solve with this feature?

Get fatal error when using model of gemini-1.5-pro-latest

---
Error raised at top level: GoogleGenerativeAI.GenerateContentError.internalError(underlying: GoogleGenerativeAI.RPCError(httpResponseCode: 404, message: "models/gemini-1.5-pro-latest is not found for API version v1, or is not supported for GenerateContent. Call ListModels to see the list of available models and their supported methods.", status: GoogleGenerativeAI.RPCStatus.notFound, details: []))

**Comment by andrewheard** [comment]
Hi @mobilinked, at the moment I'm only seeing `gemini-1.5-pro-latest` on the `v1beta` version of the API. Would you mind trying that version instead (see `RequestOptions` in the snippet below to switch from the default `v1`)?
```
let model = GenerativeModel(
  name: "gemini-1.5-pro-latest",
  apiKey: APIKey.default,
  requestOptions: RequestOptions(apiVersion: "v1beta")
)
```

**Comment by mobilinked** [comment]
It works. Thanks much.
