### ISSUE TITLE
Swift `generateEmbeddings` returns 404

### ISSUE THREAD

**Issue by Brandon7CC** [google/generative-ai-swift#13]
When attempting to use the `generateEmbeddings` implementation in `GenerativeLanguage.swift`:

```swift
public func generateEmbeddings(from text: String, model: String = "models/text-bison-001") async throws -> EmbedTextResponse {
    let embedTextRequest = EmbedTextRequest(text: text)
    let request = API.v1beta2.embedText(model).post(embedTextRequest)
    let response = try await apiClient.send(request)
    return response.value
  }
```

**I get the following: `Error: Response status code was unacceptable: 404.`**

My code looks something like:
```swift
let response = try await client.generateEmbeddings(from: text)
```

P.S. 
**Really excited** about the PaLM SDK for Swift! Thank you for "swiftly implementing" 😉 and wonderful job!

**Comment by peterfriese** [comment]
Hi Brandon, thanks for the kind words!

It sounds like you might be calling the API from outside the API. Another reason might be that you're still on the waitlist for getting access.

Can you check if the the other two sample apps work as expected?

**Comment by Brandon7CC** [comment]
Hey Peter thank you for getting back to me so quickly! I've played around with both the PaLMText and PaLMChat examples and both work well. 

Both of the underlying functions `generateText` and `chat` are also working in my app, but I'm having an issue with the call to `generateEmbeddings`. 

Here's some more context:
```swift
var client: GenerativeLanguage? = nil // initialized before API calls

// @note `generateText` works correctly in my add as does `chat`.
let response = try await client!.generateText(with: "\(securityResearchPrompt):\(text)")

// @discussion My code for generating embeddings (follows a very similar pattern to 
//             the example from `PaLMText` and) looks like:
public func embedText(text: String) async throws -> [Float] {
        do {
            let response = try await client!.generateEmbeddings(from: "Sample text.")
            return response.embedding?.value ?? []
        } catch {
            print(error.localizedDescription)
            return []
        }
    }
```

Might it be the case that I'm still on the waitlist for this specific endpoint?

**Comment by Brandon7CC** [comment]
Problem solved! Thank you for the insanely quick turnaround Peter! Much appreciated and looking forward to future updates 🥳
