### ISSUE TITLE
"Failed to resolve dependencies" error message in xcode

### ISSUE THREAD

**Issue by keneseu** [google/generative-ai-swift#29]
### Description of the bug:

Hi, received the "Package Resolution Failed" error dialog box, indicating that it "Failed to resolve dependencies", while attempting to add this package to xcode 13.4.1. If I selected "Add Anyway", I would be unable to import "GoogleGenerativeAI" to be used.

### Actual vs expected behavior:

I think that the package should be added without error. Would appreciate any advice or help. Thank you.

**Comment by paulb777** [comment]
Sorry about the trouble. The Palm SDK requires Xcode 14 and future versions of the SDK will require Xcode 15.
