### ISSUE TITLE
Add instructions for using the SDK in a Swift Playground

### ISSUE THREAD

**Issue by andrewheard** [google/generative-ai-swift#72]
### Description of the feature request:

- Add instructions in one of the README files for using the SDK in a Swift Playground
  - On iPadOS this is just a matter of adding `https://github.com/google/generative-ai-swift.git` as a Package dependency (i.e., it just works)
  - On macOS you also need to add the client networking entitlement

**Comment by paulb777** [comment]
No plans now.
