### ISSUE TITLE
Are there any plans to support macOS 11.0?

### ISSUE THREAD

**Issue by tisfeng** [google/generative-ai-swift#83]
### Description of the feature request:

My app supports macOS 11.0+, I want to add Gemini and I found out that this library requires macOS 12.0, do you have any plans to support macOS 11.0?

If not, is there another way to make this library available to macOS 11.0 apps?

### What problem are you trying to solve with this feature?

After upgrading the minimum version of the project to macOS 12, I successfully connected to Gemini, and there was no problem.

**Comment by andrewheard** [comment]
Hi @tisfeng, would this still be useful to you if only the non-streaming APIs were available on macOS 11? (#84 for context)

**Comment by tisfeng** [comment]
Thanks, it's nice that we can use non-streaming APIs on macOS 11 😃

**Comment by andrewheard** [comment]
Glad to hear the non-streaming APIs will work for you! I just published https://github.com/google/generative-ai-swift/releases/tag/0.4.5 so you should be able to start using these now 😄 

Closing this issue now. Thank you for submitting this feature request, let us know if you have more in the future!
